export interface IRegistration {
  registrationId: string,
  participantFirstName: string,
  participantLastName: string,
  schoolName: string,
  dob: string,
  grade: number,
  team: string,
  streetAddress: string,
  city: string,
  state: string,
  zipCode: string,
  motherFirstName: string,
  motherLastName: string,
  motherPhoneNum: string,
  fatherFirstName: string,
  fatherLastName: string,
  fatherPhoneNum: string,
  email: string,
};
